blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/buildwarden/buildwarden/discussions
    about: For questions, ideas, and general discussion about BuildWarden
