FROM ubuntu:latest

RUN apt update && \
    apt install -y \
        cmake \
        g++ \
        libedit-dev \
        git \
        wget \
    && \
    wget -O llvm "https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang-14.0.6.src.tar.xz"
