FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ make cmake && \
    rm -rf /var/lib/apt/lists/*
RUN pip install conan
RUN conan profile detect
RUN conan install --requires=zlib/1.3.1 --build=missing
