FROM python:3.12-slim

# Install Poetry
RUN pip install poetry

WORKDIR /app

# Initialize a new project
RUN poetry init --name test --no-interaction

# Add a dependency
RUN poetry add requests==2.32.3
