name: auto-tidy

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  auto-tidy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make tidy
      - run: make lint
      - run: make build
      - run: ./warden --help
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: go mod tidy'
